[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'junegunn/seoul256.vim'

[[plugins]]
repo = 'junegunn/fzf'
build = './install'
merged = 0
hook_add = '''
function! s:find_git_root()
  return system('git rev-parse --show-toplevel 2> /dev/null')[:-2]
endfunction
command! -bang -nargs=* GGrep
  \ call fzf#vim#grep(
  \   'pt --column --ignore=.git --global-gitignore '.shellescape(<q-args>), 1,
  \   <bang>0 ? fzf#vim#with_preview('up:60%')
  \           : fzf#vim#with_preview({ 'dir': s:find_git_root() }),
  \   <bang>0)
'''

[[plugins]]
repo = 'junegunn/fzf.vim'
hook_add = '''
let g:fzf_history_dir = '~/.cache/nvim/fzf-history'
'''

[[plugins]]
repo = 'Shougo/deoplete.nvim'
hook_add = '''
let g:deoplete#enable_at_startup = 1
let g:deoplete#enable_camel_case = 0
let g:deoplete#enable_ignore_case = 0
let g:deoplete#enable_smart_case = 1
let g:deoplete#auto_complete_delay = 0
let g:deoplete#auto_refresh_delay = 100
let g:deoplete#enable_buffer_path = 1
let g:deoplete#tag#cache_limit_size = 500000
'''

[[plugins]]
repo = 'tpope/vim-fugitive'

[[plugins]]
repo = 'tpope/vim-surround'

[[plugins]]
repo = 'glidenote/memolist.vim'
hook_add = '''
let g:memolist_gfixgrep             = 1
let g:memolist_filename_prefix_none = 1

nmap mn  :MemoNew<CR>
nmap mg  :MemoGrep<CR>
'''

[[plugins]]
repo = 'previm/previm'
hook_add = '''
let g:previm_show_header = 0
'''

[[plugins]]
repo = 'plasticboy/vim-markdown'

[[plugins]]
repo = 'tpope/vim-commentary'

[[plugins]]
repo = 'tyru/open-browser.vim'

[[plugins]]
repo = 'cespare/vim-toml'
on_ft = 'toml'

[[plugins]]
repo = 'fatih/vim-go'
on_ft = 'go'
hook_add = '''
let g:go_fmt_command = "goimports"
let g:go_metalinter_autosave_enabled = ['vet', 'golint']
au FileType go nmap <leader>r <Plug>(go-run)
au FileType go nmap <leader>b <Plug>(go-build)
au FileType go nmap <leader>t <Plug>(go-test)
au FileType go nmap <leader>c <Plug>(go-coverage)

au FileType go nmap <Leader>ds <Plug>(go-def-split)
au FileType go nmap <Leader>dv <Plug>(go-def-vertical)
au FileType go nmap <Leader>dt <Plug>(go-def-tab)

au FileType go nmap <Leader>gd <Plug>(go-doc)
au FileType go nmap <Leader>gv <Plug>(go-doc-vertical)
'''

[[plugins]]
repo = 'othree/yajs.vim'
on_ft = ['javascript', 'vue']

[[plugins]]
repo = 'kchmck/vim-coffee-script'
on_ft = 'coffee'

[[plugins]]
repo = 'leafgarland/typescript-vim'
on_ft = 'typescript'

[[plugins]]
repo = 'hashivim/vim-terraform'
hook_add = '''
let g:terraform_align=1
let g:terraform_fmt_on_save=1
'''

[[plugins]]
repo = 'rust-lang/rust.vim'
on_ft = 'rust'
hook_add = '''
let g:rustfmt_autosave = 1
'''

[[plugins]]
repo = 'w0rp/ale'
hook_add = '''
let g:ale_linters = {
  \ 'html': [],
  \ 'css': ['stylelint'],
  \ 'javascript': ['eslint'],
  \ 'vue': ['eslint']
  \ }
let g:ale_linter_aliases = {'vue': 'css'}
'''
